---
title: "Analysis_for_DraftReport"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rvest)
library(stringr)
library(ggplot2)
```

#### Webscraping https://www.univcan.ca/universities/facts-and-stats/tuition-fees-by-university/
```{r}
URL = 'https://www.univcan.ca/universities/facts-and-stats/tuition-fees-by-university/'
page = read_html(url(URL))

univcan_data =   
  page %>% 
  html_nodes(xpath = '//*[@id="data_table"]') %>%
  html_table(fill = TRUE) %>% 
  as.data.frame()
univcan_data = univcan_data[-1,]
univcan_data
```

#### Setting up the data in interest
```{r}
domestic_undergraduate =
  univcan_data %>% 
  mutate(domestic_undergraduate_tuition = str_extract(Undergraduate, "(\\d+)[^-*]*$")) %>% 
  select(University, domestic_undergraduate_tuition) %>% na.omit()

domestic_undergraduate$domestic_undergraduate_tuition =
  as.numeric(gsub(",","",domestic_undergraduate$domestic_undergraduate_tuition))

domestic_undergraduate
######################################################################################################################
international_undergraduate =
  univcan_data %>% 
  mutate(international_undergraduate_tuition = str_extract(Undergraduate.1, "(\\d+)[^-*]*$")) %>% 
  select(University, international_undergraduate_tuition) %>% na.omit()

international_undergraduate$international_undergraduate_tuition = 
  as.numeric(gsub(",","", international_undergraduate$international_undergraduate_tuition))

international_undergraduate
######################################################################################################################
domestic_graduate =
  univcan_data %>% 
  mutate(domestic_graduate_tuition = str_extract(Graduate, "(\\d+)[^-*]*$")) %>% 
  select(University, domestic_graduate_tuition) %>% na.omit()

domestic_graduate$domestic_graduate_tuition = 
  as.numeric(gsub(",", "", domestic_graduate$domestic_graduate_tuition))

domestic_graduate
######################################################################################################################
international_graduate =
  univcan_data %>% 
  mutate(international_graduate_tuition = str_extract(Graduate.1, "(\\d+)[^-*]*$")) %>% 
  select(University, international_graduate_tuition) %>% na.omit()

international_graduate$international_graduate_tuition = 
  as.numeric(gsub(",","", international_graduate$international_graduate_tuition))

international_graduate
```


#### DATA ANAYLSIS

#### Q1: Get a bachelor's tuition (international vs. domestic)
```{r}
domestic_undergraduate %>% 
  arrange(domestic_undergraduate_tuition) %>% 
  ggplot(aes(x=University, y = domestic_undergraduate_tuition)) + geom_point()

international_undergraduate %>% 
  arrange(international_undergraduate_tuition) %>% 
  ggplot(aes(x=University, y = international_undergraduate_tuition)) + geom_point()
```


#### Shows Domestic vs. International (used LEFT JOIN)
```{r}
domestic_international_undergraduate = 
  left_join(domestic_undergraduate, international_undergraduate, by = "University")

domestic_international_undergraduate %>% 
  ggplot(aes(x = University, y = Tuition, color = TypeOfStudent)) + 
  geom_point(aes(y = domestic_undergraduate_tuition, col = "Domestic")) + 
  geom_point(aes(y = international_undergraduate_tuition, col = "International"))
```


#### Q2: Get a masters (international vs. domestic)
```{r}
domestic_graduate %>% 
  arrange(domestic_graduate_tuition) %>% 
  ggplot(aes(x=University, y = domestic_graduate_tuition)) + geom_point()

international_graduate %>% 
  arrange(international_graduate_tuition) %>% 
  ggplot(aes(x=University, y = international_graduate_tuition)) + geom_point()
```


#### Shows Domestic vs. International (used LEFT JOIN)
```{r}
domestic_international_graduate = 
  left_join(domestic_graduate, international_graduate, by = "University")

domestic_international_graduate %>% 
  ggplot(aes(x = University, y = Tuition, color = TypeOfStudent)) + 
  geom_point(aes(y = domestic_graduate_tuition, col = "Domestic")) + 
  geom_point(aes(y = international_graduate_tuition, col = "International"))
```