---
title: "STAA57 Final Project Report "
author: "Team 10 (Daniela Venturo Esaine, Reizwan Chodhury, Ralph Samson Lal, Xiaotong Ye)"
output: html_notebook
---


***

<!-- 
(everything below in here is an .html comment)

Instructions: 
- Use typical structure of data analysis report, w/ sections:
    + Introduction
    + Data
    + Analysis
    + Summary
    + Appendix (optional)
- Report should be 5 pages MAX (when compiled/knit as pdf)
- Appendix does not count towards page limit
- Put all your data in a separate "./data/" sub-folder 
- Submit compressed project folder 
- You submissions should be reproducible (i.e. I should be able to   
  re-compile your report with a click of the Preview/Knit button) 

-->

## Introduction 

"Is university worth it?" is one of the hardest questions to answer. University is a very different experience from person to person depending on various factors. One of the main worries of most people is the heavy economical investment university takes. This skews the question towards the idea of measuring worth by future economical gain that cancels out the original investment. Therefore, to investigate if university is worth it, it makes sense to calculate the amount of time it takes to amortize total tuition cost in Canada.

Since tuition expenses show great variance depending on factors such as nationality, type of degree, or field of study, to have a relevant conclusion it is necessary to answer the following questions:

1. Is it worth it to get a Bachelor's degree as a Canadian domestic student compared to an international student?
2. Is it worth it to get a Masters degree as a Canadian domestic student compared to an international student?
3. What is the most "worth-it" field of study? (for undergraduate and graduate, for international and domestic)
4. What is the least "worth-it" field of study? (for undergraduate and graduate, for international and domestic)
5. Who has a bigger rate of unemployment? Bachelor degrees or master degrees?

## Data 

To answer the questions stated above it is required to get tuition costs depending on graduate and undergraduate levels of study and fields of study. To do that we will webscrape data from univcan.ca that will let us know the average tuition for graduate and undergraduate degrees. Tables from statcan will indicate the average tuition for international and domestic students at different fields of study as well as different levels of study. Unemployment and income data will be processed from csv files obtained from census data from CFS and LFS. 

#### DATA ANAYLSIS

#### Q1: Get a bachelor's tuition (international vs. domestic)

#### Q2: Get a masters (international vs. domestic)

#### Q3: Most worth it field of study. (for undergraduate and graduate, for international and domestic)

#### Q4: Least worth it field of study. (for undergraduate and graduate, for international and domestic)
```{r}
can-undergrad = read_csv("data/can-undergrad.csv")
can-grad = read_csv("data/can-grad.csv")
inter-undergrad = read_csv("data/inter-undergrad.csv")
inter-grad = read_csv("data/inter-grad.csv")
```

#### Q4: Comment on unemployment

## Summary 

Based on the results from question 1 and 2, it is safe to conclude that International student tuition for any degree is higher than Domestic student tuition. However, the gap between tuition is lessened when going from a bachelor's degree to a masters degree. This means it is easier to pay off a masters than a bachelors degree as an international student. Domestic student tuition fees are generally lower. In the end, both are worth it.

According to the answers to question 3, if one does not get a job right after completing an undergraduate degree, it is recommendable to take a masters right after completion of a bachelors because the cost of living is paid during that time. However, if one is employed and has a constant source of income, the difference is not significant, in which case one can choose freely if to take the masters degree now or wait a few years.

Moving on, based on the results for questions 4 and 5 we find the most worth it field of study is Dental, medical and veterinary residency programs, with law in second place. This means it will have the highest payout out of all other degrees. The "least worth it" field of study is. However, by no means does this imply it is not worth it. Education is an investment, the statistics calculated just implies it is harder to get a good payout from that field.

To comment on unemployment, the degree of your study does affect greatly on the chances of being unemployed as the difference in the duration of unemployment is very significant between the two. Therefore it is recommendable to get a masters degree.


***  

## Appendix 

(*Everything here does not count towards page limit*)


